// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "ABTSM3TaskGraphTypes.generated.h"

UENUM(BlueprintType)
enum class EABTSM3TaskType : uint8
{
	Unassigned,
	Start,
	Workshop,
	SlingshotRange,
	TargetBuilding,
	BridgeGate,
	FurnaceRuins,
	LaunchSite,
	Scout,
	SatelliteWindow
};

UENUM(BlueprintType)
enum class EABTSM3TerrainType : uint8
{
	Plain,
	Forest,
	Highland,
	Mountain,
	Water
};

USTRUCT(BlueprintType)
struct FABTSM3TaskNode
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	int32 TaskId = INDEX_NONE;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	EABTSM3TaskType Type = EABTSM3TaskType::Unassigned;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	int32 SeedCellId = INDEX_NONE;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	TArray<int32> CellIds;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	TArray<int32> LinkedTaskIds;
};

USTRUCT(BlueprintType)
struct FABTSM3CellState
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	int32 TaskId = INDEX_NONE;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	EABTSM3TerrainType TerrainType = EABTSM3TerrainType::Plain;

	/** Logical macro height normalized to [0,1]. It is generated by PCG, not sampled from the render mesh. */
	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	float LogicalHeight01 = 0.0f;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	int32 RoadDistance = MAX_int32;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	bool bRoad = false;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	bool bWater = false;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|TaskGraph")
	bool bBuildingAnchor = false;
};

USTRUCT(BlueprintType)
struct FABTSM3BuildingSpawnSite
{
	GENERATED_BODY()

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|Building")
	int32 CellId = INDEX_NONE;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|Building")
	EABTSM3TaskType TaskType = EABTSM3TaskType::Unassigned;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|Building")
	FTransform WorldTransform = FTransform::Identity;

	UPROPERTY(VisibleAnywhere, BlueprintReadOnly, Category = "ABTS|M3|Building")
	float MaxSlopeDegrees = 0.0f;
};

